### PR TITLE
Handle own cluster subscription release

### LINKED ISSUE #2545: Handle own_cluster plan in Release_Subscription step
**Description**

During testing of the deprovisioning retrigger we discoverd that the `Release_Subscription` step doesn't take into account the `own_cluster` plan. Only an error is logged without failing this step and the deprovisioning process continues. We didn't notice this error before because KCP CLI doesn't show the `Release_Subscription` event as an error 

> kcp rt -i 2dd5f8e4-261d-4209-bebd-e605737cfb49 --only-deleted --events
>
> ˫ info   33h                         processing step: Release_Subscription  

when something goes wrong and the only way to discover it was to manually check the logs. With the new deprovision retrigger logic it is possible to detect a step like this using the `-o json` flag 

> kcp rt -i 2dd5f8e4-261d-4209-bebd-e605737cfb49 -o json --only-deleted
>
> "executedButNotCompletedSteps": [
>             "Release_Subscription"
>           ],

**AC**

- [x] handle the own_cluster plan in the Release_Subscription step

### PR DESCRIPTION
**Pull request by MarekMichali**
**Description**

`OwnCluster` is not handled properly in the `release_subscription` step and a wrong assertion is used in `TestReleaseSubscriptionStep_TrialPlan`. This PR fixes it.

Changes proposed in this pull request:

- Handle `OwnCluster` plan
- Add test case for `OwnCluster` plan
- Fix assertions for `TrialPlan`

**Related issue(s)**

Resolves #2545

### CODE REVIEW

File: components/kyma-environment-broker/internal/process/deprovisioning/release_subscription_step.go [hunk 1]
```diff
@@ -36,7 +36,7 @@ func (s ReleaseSubscriptionStep) Name() string {
 func (s ReleaseSubscriptionStep) Run(operation internal.Operation, log logrus.FieldLogger) (internal.Operation, time.Duration, error) {
 
 	planID := operation.ProvisioningParameters.PlanID
-	if !broker.IsTrialPlan(planID) {
+	if !broker.IsTrialPlan(planID) && !broker.IsOwnClusterPlan(planID) {
```
Comment (jaroslaw-pieszka) [inline components/kyma-environment-broker/internal/process/deprovisioning/release_subscription_step.go:39]: Could you demorgenize?

Comment (jaroslaw-pieszka) [reply components/kyma-environment-broker/internal/process/deprovisioning/release_subscription_step.go:39]: Unless you think that this version is easier to read.

Comment (jaroslaw-pieszka) [reply components/kyma-environment-broker/internal/process/deprovisioning/release_subscription_step.go:39]:
```suggestion
	if !(broker.IsTrialPlan(planID) || broker.IsOwnClusterPlan(planID)) {
```

**Review by ralikio — APPROVED** [review]

**Review by jaroslaw-pieszka — APPROVED** [review]
