### PR TITLE
Fail process if overrides not found

### LINKED ISSUE #2378: KEB Overrides_From_Secrets_And_Config steps must fail if overrides not found
**Description**

Overrides_From_Secrets_And_Config are looking for static overrides for given version and plan. If not found, the process must fail instead of retry, which does not make sense.

**Expected result**

Steps fails in case of no overrides available

**Actual result**

Steps are retrying.

### PR DESCRIPTION
**Pull request by MarekMichali**
**Description**

Changes proposed in this pull request:

- Change retry to fail if overrides not found

**Related issue(s)**

Resolves #2378

### CODE REVIEW

File: components/kyma-environment-broker/internal/process/upgrade_kyma/secret_cm_overrides.go [hunk 1]
```diff
@@ -50,7 +50,7 @@ func (s *OverridesFromSecretsAndConfigStep) Run(operation internal.UpgradeKymaOp
 
 	version, err := s.getRuntimeVersion(operation)
 	if err != nil {
-		return s.operationManager.RetryOperation(operation, "error while getting runtime version", err, 5*time.Second, 5*time.Minute, log)
+		return s.operationManager.OperationFailed(operation, "error while getting runtime version", err, log)
```
Comment (jaroslaw-pieszka) [inline components/kyma-environment-broker/internal/process/upgrade_kyma/secret_cm_overrides.go:53]: Isn't it reflected in any test?

Comment (MarekMichali) [reply components/kyma-environment-broker/internal/process/upgrade_kyma/secret_cm_overrides.go:53]: The tests are covering only successfully executions.

**Review by jaroslaw-pieszka — APPROVED** [review]
